services:
  jellyfin:
    image: jellyfin/jellyfin:2025072105
    container_name: jellyfin
    env_file: .env

    volumes:
      - /srv/jellyfin/cache:/cache
      - /srv/jellyfin/config:/config
      - /media:/media

    ports:
      - "1900:1900/tcp"
      - "7359:7359/udp"
      - "8096:8096/tcp"

    restart: unless-stopped

    networks:
      - default

networks:
  default:
